# Generated by Django 5.2.4 on 2026-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_request', 'Appointment Request'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_completed', 'Appointment Completed'), ('staff_assigned', 'Staff Assigned'), ('shift_update', 'Shift Update'), ('holiday_approved', 'Holiday Approved'), ('overtime_approved', 'Overtime Approved')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
