# Generated by Django 5.2.4 on 2026-03-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_settings', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='user.staff'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='user.staff'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='user.staff'),
        ),
        migrations.AddField(
            model_name='shift',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='user.hospital'),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='from_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_from', to='staff_settings.shift'),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_change_requests', to='user.staff'),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='to_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_to', to='staff_settings.shift'),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='staff_settings.shift'),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='user.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staffshift',
            unique_together={('staff', 'shift', 'effective_from')},
        ),
    ]
