# Generated by Django 5.2.4 on 2025-12-07 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('communication_method', models.CharField(choices=[('onsite', 'Onsite'), ('video', 'Video call'), ('voice', 'Voice call')], max_length=10)),
                ('confirmed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user.patient')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='user.staff')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='appointment_hospita_2b6267_idx'), models.Index(fields=['patient', 'requested_date'], name='appointment_patient_0dfcc1_idx')],
            },
        ),
    ]
