# Generated by Django 5.2.4 on 2026-03-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('communication_method', models.CharField(choices=[('onsite', 'Onsite'), ('video', 'Video call'), ('voice', 'Voice call')], max_length=10)),
                ('confirmed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
